// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzI5603YR6q_FgBT23Xr_XsQlxOLRzpUk',
    appId: '1:860433568497:web:dba9753d3a524f95754f50',
    messagingSenderId: '860433568497',
    projectId: 'app-posto-ic',
    authDomain: 'app-posto-ic.firebaseapp.com',
    storageBucket: 'app-posto-ic.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCR-UZev8vG_HR7-iuGWY1CFtwgj8oBZw',
    appId: '1:860433568497:android:442e1c9eb18d0da4754f50',
    messagingSenderId: '860433568497',
    projectId: 'app-posto-ic',
    storageBucket: 'app-posto-ic.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnodjMT7lR0fLm2WRoMFBJ4q1-Xd6Sncc',
    appId: '1:860433568497:ios:e281eb220acba323754f50',
    messagingSenderId: '860433568497',
    projectId: 'app-posto-ic',
    storageBucket: 'app-posto-ic.firebasestorage.app',
    iosBundleId: 'com.example.virtualTherapyApp',
  );
}
