// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTjj4VXrHaq8db-kVkEGrmUWyOpdnRYwM',
    appId: '1:550051810513:web:b519143cd5f0ea4f7689f0',
    messagingSenderId: '550051810513',
    projectId: 'ic-posto',
    authDomain: 'ic-posto.firebaseapp.com',
    storageBucket: 'ic-posto.firebasestorage.app',
    measurementId: 'G-QYE46V9YTM', // opcional
  );


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB39SQ6Ows0APr_MG1KE-D3lNef0UV540',
    appId: '1:550051810513:android:c708c6fda55d3c1a7689f0',
    messagingSenderId: '550051810513',
    projectId: 'ic-posto',
    storageBucket: 'ic-posto.firebasestorage.app',
  );


  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuIfotFaRaecebKV2EXS_OXxbOVsD-LKk',
    appId: '1:550051810513:ios:27a8690de2fa91327689f0',
    messagingSenderId: '550051810513',
    projectId: 'ic-posto',
    storageBucket: 'ic-posto.firebasestorage.app',
    iosBundleId: 'com.icposto',
  );

}
